# Generated by Django 6.0.2 on 2026-02-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('Department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('Class_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('room_number', models.CharField(max_length=20)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments'),
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('Exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('total_marks', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('Enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('grade', models.CharField(max_length=2)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classes')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('Teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teachers'),
        ),
    ]
